"""Shared application services."""

from .artifact_service import select_flash_artifact
from .cubemx_host_service import (
    configured_cubemx_log_path,
    cubemx_tool_entry,
    derive_cubemx_candidates,
    derive_java_candidates,
    discover_cubemx,
    load_build_metadata,
    load_cubemx_metadata,
    load_firmware_metadata,
    project_section_metadata,
    resolve_cubemx_launcher,
    resolve_java_path,
)
from .cubemx_inspection_service import build_cubemx_capabilities, parse_ioc_summary
from .cubemx_log_service import write_cubemx_log
from .cubemx_runtime_service import (
    cubemx_failure_reason,
    cubemx_script_reports_success,
    run_cubemx_command,
    run_cubemx_command_with_progress,
    terminate_cubemx_process,
)
from .cubemx_tool_service import (
    orchestrate_cubemx_regeneration,
    parse_cubemx_ioc,
    regenerate_cubemx_project,
    report_cubemx_capabilities,
)
from .ioc_builder_service import (
    apply_ioc_change_set as apply_ioc_change_set_service,
    collect_ioc_builder_capabilities,
    compile_ioc_plan,
    construct_ioc_file as construct_ioc_file_service,
)
from .project_config_service import (
    configured_cubemx_request,
    configured_firmware_artifact,
    derived_project_paths,
    ensure_project_metadata_for_feature_contract,
    inferred_project_name,
    inferred_project_toolchain,
    merge_project_metadata_with_prompt_fallback,
    normalize_cubemx_toolchain,
    normalize_project_config,
    workspace_project_metadata_path,
)
from .routing_service import WorkflowRoute, classify_prompt, extract_file_path, is_debug_question
from .workflow_state import (
    contract_feature_ids,
    contract_feature_lookup,
    contract_for_increment,
    contract_increment_records,
    interface_intent_lookup,
    ioc_plan_details,
    next_pending_increment,
    reusable_cubemx_result_from_ioc_validation,
    summarize_execution_policy,
    summarize_ioc_validation,
    with_effective_ioc_path,
)

__all__ = [
    "WorkflowRoute",
    "classify_prompt",
    "extract_file_path",
    "is_debug_question",
    "select_flash_artifact",
    "project_section_metadata",
    "load_firmware_metadata",
    "load_build_metadata",
    "load_cubemx_metadata",
    "configured_cubemx_log_path",
    "cubemx_tool_entry",
    "derive_cubemx_candidates",
    "derive_java_candidates",
    "resolve_java_path",
    "discover_cubemx",
    "resolve_cubemx_launcher",
    "build_cubemx_capabilities",
    "parse_ioc_summary",
    "report_cubemx_capabilities",
    "parse_cubemx_ioc",
    "regenerate_cubemx_project",
    "orchestrate_cubemx_regeneration",
    "collect_ioc_builder_capabilities",
    "compile_ioc_plan",
    "apply_ioc_change_set_service",
    "construct_ioc_file_service",
    "write_cubemx_log",
    "terminate_cubemx_process",
    "cubemx_script_reports_success",
    "cubemx_failure_reason",
    "run_cubemx_command_with_progress",
    "run_cubemx_command",
    "normalize_cubemx_toolchain",
    "workspace_project_metadata_path",
    "derived_project_paths",
    "inferred_project_name",
    "inferred_project_toolchain",
    "merge_project_metadata_with_prompt_fallback",
    "ensure_project_metadata_for_feature_contract",
    "normalize_project_config",
    "configured_cubemx_request",
    "configured_firmware_artifact",
    "with_effective_ioc_path",
    "ioc_plan_details",
    "summarize_ioc_validation",
    "reusable_cubemx_result_from_ioc_validation",
    "summarize_execution_policy",
    "contract_feature_ids",
    "contract_feature_lookup",
    "contract_increment_records",
    "interface_intent_lookup",
    "contract_for_increment",
    "next_pending_increment",
]
